version: "3"

services:
  rdtclient:
    image: "rogerfar/rdtclient:latest"
    container_name: rdtclient
    restart: unless-stopped
    hostname: "rdtclient"
    volumes:
      - './rdtclient/downloads:/data/downloads'
      - './rdtclient/config:/data/db'
    logging:
      driver: json-file
      options:
        max-size: 10m
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      private_network:
        ipv4_address: 10.2.0.10
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.11
  #jackett:
  #  image: "linuxserver/jackett:latest"
  #  container_name: jackett
  # restart: unless-stopped
  #  hostname: "jackett"
  #  volumes:
  #    - './jackett/downloads:/data/downloads'
  #    - './jackett/config:/config'
  #  environment:
  #    - PUID=1000
  #   - PGID=1000
  #    - TZ=America/New_York
  #    - AUTO_UPDATE=true #optional
  #  networks:
  #    private_network:
  #      ipv4_address: 10.2.0.11
  
  flaresolverr:
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    container_name: flaresolverr
    restart: unless-stopped
    hostname: "flaresolverr"
    environment:
      - LOG_LEVEL=info
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      private_network:
        ipv4_address: 10.2.0.12
  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: sonarr
    restart: unless-stopped
    hostname: "sonarr"
    volumes:
      - './sonarr/series:/tv'
      - './rdtclient/downloads/sonarr:/downloads/sonarr'
      - './sonarr/config:/config'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      private_network:
        ipv4_address: 10.2.0.13
  radarr:
    image: "linuxserver/radarr:latest" #use always the latest image
    container_name: radarr
    restart: unless-stopped
    hostname: "radarr"
    volumes:
      - './radarr/movies:/movies'
      - './rdtclient/downloads/radarr:/downloads/radarr'
      - './radarr/config:/config'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      private_network:
        ipv4_address: 10.2.0.14

  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=03:00 #optional
      - PMM_RUN=False #optional
      - PMM_TEST=False #optional
      - PMM_NO_MISSING=False #optional
    volumes:
      - ./plexmm/config:/config
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.15


        
networks:
      private_network:
        external:
          name: wirepius_private_network
